from datetime import datetime
from sqlmodel import SQLModel, Field

class TrendAnalysis(SQLModel, table=True):
    """
    Stores the final result of a Trend Radar analysis session.
    """
    __tablename__ = "trend_analyses"
    
    id: int | None = Field(default=None, primary_key=True)
    time_window_days: int # e.g., 7, 30
    paper_count: int
    
    # JSON strings for structured data
    # Format: {"NLP": 45, "CV": 30, "Robotics": 10}
    domain_distribution_json: str

    # Format: {"LoRA": 15, "Quantization": 12}
    top_techniques_json: str

    # Format: { "NLP": [{"id": "...", "title": "..."}, ...] }
    # Stores mapping from Domain to list of reference papers
    domain_references_json: str = Field(default="{}")

    # Format: { "LoRA": [{"id": "...", "title": "..."}, ...] }
    # Stores mapping from Technique to list of reference papers
    technique_references_json: str = Field(default="{}")

    # The Markdown report generated by AI
    report_markdown: str

    created_at: datetime = Field(default_factory=datetime.now)


class PaperTagCache(SQLModel, table=True):
    """
    Caches AI-extracted tags for papers to avoid redundant LLM calls.
    """
    __tablename__ = "paper_tag_cache"
    
    paper_id: str = Field(primary_key=True) # ArXiv ID
    # JSON: {"domain": "NLP", "task": "Reasoning", "techniques": ["CoT", "Prompting"]}
    tags_json: str
    updated_at: datetime = Field(default_factory=datetime.now)