"""
SQLModel models for trend analysis feature.

This module defines the database models for:
- **TrendAnalysis**: Stores the final result of a Trend Radar analysis session,
  including domain distributions, top techniques, reference papers, and the
  AI-generated markdown report.
- **PaperTagCache**: Caches AI-extracted tags for papers to avoid redundant
  LLM API calls, improving performance and reducing costs.
"""

from datetime import datetime
from sqlmodel import SQLModel, Field

class TrendAnalysis(SQLModel, table=True):
    """
    Stores the final result of a Trend Radar analysis session.

    This model persists the complete analysis output including:
    - Statistical summaries (domain distribution, top techniques).
    - Reference paper mappings for evidence-based citations.
    - The full AI-generated markdown report.

    Attributes:
        id (int | None): Primary key, auto-generated.
        time_window_days (int): The analysis time window in days (e.g., 7, 30).
        paper_count (int): Total number of papers analyzed.
        domain_distribution_json (str): JSON string of domain counts
            (e.g., `{"NLP": 45, "CV": 30, "Robotics": 10}`).
        top_techniques_json (str): JSON string of technique counts
            (e.g., `{"LoRA": 15, "Quantization": 12}`).
        domain_references_json (str): JSON mapping from domain to list of
            reference papers `{ "NLP": [{"id": "...", "title": "..."}, ...] }`.
        technique_references_json (str): JSON mapping from technique to list of
            reference papers `{ "LoRA": [{"id": "...", "title": "..."}, ...] }`.
        report_markdown (str): The full markdown report generated by AI.
        created_at (datetime): Timestamp when the analysis was created.

    Table:
        __tablename__: "trend_analyses"
    """
    __tablename__ = "trend_analyses"

    id: int | None = Field(default=None, primary_key=True)
    time_window_days: int
    paper_count: int

    # JSON strings for structured data
    # Format: {"NLP": 45, "CV": 30, "Robotics": 10}
    domain_distribution_json: str

    # Format: {"LoRA": 15, "Quantization": 12}
    top_techniques_json: str

    # Format: { "NLP": [{"id": "...", "title": "..."}, ...] }
    # Stores mapping from Domain to list of reference papers
    domain_references_json: str = Field(default="{}")

    # Format: { "LoRA": [{"id": "...", "title": "..."}, ...] }
    # Stores mapping from Technique to list of reference papers
    technique_references_json: str = Field(default="{}")

    # The Markdown report generated by AI
    report_markdown: str

    created_at: datetime = Field(default_factory=datetime.now)


class PaperTagCache(SQLModel, table=True):
    """
    Caches AI-extracted tags for papers to avoid redundant LLM calls.

    This model stores pre-computed metadata tags for each paper, including:
    - Domain classification (e.g., NLP, CV, Robotics).
    - Research task description.
    - Techniques mentioned in the paper.

    Attributes:
        paper_id (str): Primary key, the ArXiv paper ID.
        tags_json (str): JSON string containing extracted tags
            (e.g., `{"domain": "NLP", "task": "Reasoning", "techniques": ["CoT", "Prompting"]}`).
        updated_at (datetime): Timestamp when the cache was last updated.

    Table:
        __tablename__: "paper_tag_cache"
    """
    __tablename__ = "paper_tag_cache"

    paper_id: str = Field(primary_key=True)  # ArXiv ID
    # JSON: {"domain": "NLP", "task": "Reasoning", "techniques": ["CoT", "Prompting"]}
    tags_json: str
    updated_at: datetime = Field(default_factory=datetime.now)