"""
Data Transfer Objects (DTOs) for trend analysis API.

This module defines Pydantic models for:
- **TrendAnalysisResponse**: The complete trend analysis result returned to clients.
- **TrendGenerateRequest**: Request payload for generating trend reports.
- **TrendTaskResponse**: Response for async task initiation.
- **TrendStatusResponse**: Polling response for async task status.
"""

from pydantic import BaseModel, Field
from typing import Dict, List, Optional
from datetime import datetime

class TrendAnalysisResponse(BaseModel):
    """
    Response model containing the complete trend analysis result.

    This model is used to return the full analysis output to API clients,
    including statistical summaries, reference papers, and the AI-generated report.

    Attributes:
        id (int): The unique identifier of the analysis record.
        time_window_days (int): The analysis time window in days.
        paper_count (int): Total number of papers analyzed.
        domain_distribution (Dict[str, int]): Domain counts
            (e.g., `{"NLP": 45, "CV": 30}`).
        top_techniques (Dict[str, int]): Technique counts
            (e.g., `{"LoRA": 15, "Quantization": 12}`).
        domain_references (Dict[str, List[Dict[str, str]]]): Reference papers
            grouped by domain `{ "Domain_Name": [{"id": "...", "title": "..."}, ...] }`.
        technique_references (Dict[str, List[Dict[str, str]]]): Reference papers
            grouped by technique `{ "Technique": [{"id": "...", "title": "..."}, ...] }`.
        report_markdown (str): The full markdown report generated by AI.
        created_at (datetime): Timestamp when the analysis was created.
    """
    id: int
    time_window_days: int
    paper_count: int
    domain_distribution: Dict[str, int]
    top_techniques: Dict[str, int]
    # Reference map by domain: { "Domain_Name": [{"id": "...", "title": "..."}, ...] }
    domain_references: Dict[str, List[Dict[str, str]]]
    # Reference map by technique: { "Technique": [{"id": "...", "title": "..."}, ...] }
    technique_references: Dict[str, List[Dict[str, str]]]
    report_markdown: str
    created_at: datetime

class TrendGenerateRequest(BaseModel):
    """
    Request model for generating a trend analysis report.

    This model defines the parameters for customizing the trend analysis,
    including time window, search filters, and paper limits.

    Attributes:
        days (int): Time window in days (1-30, default: 7).
        query (str): Optional keyword filter for paper search (default: "").
        categories (List[str]): List of ArXiv categories to search
            (e.g., `["cs.AI", "cs.LG"]`).
        max_papers (int): Maximum number of papers to analyze (10-500, default: 200).
    """
    days: int = Field(default=7, ge=1, le=30, description="Time window in days")
    query: str = Field(default="", description="Optional keyword filter")
    categories: List[str] = Field(default=[], description="List of ArXiv categories")
    max_papers: int = Field(default=200, ge=10, le=500, description="Max papers to analyze")

class TrendTaskResponse(BaseModel):
    """
    Response model for initiating an async trend generation task.

    This model returns a task ID that can be used to poll for status updates.

    Attributes:
        task_id (str): Unique identifier for the background task.
        message (str): Status message confirming task initiation.
    """
    task_id: str
    message: str

class TrendStatusResponse(BaseModel):
    """
    Response model for polling the status of an async trend generation task.

    This model provides real-time progress updates during report generation,
    including status, progress percentage, and the final result when complete.

    Attributes:
        task_id (str): Unique identifier for the background task.
        status (str): Current task status ('pending', 'processing', 'completed', 'failed').
        progress (int): Progress percentage (0-100).
        message (str): Human-readable status message
            (e.g., "Fetching from ArXiv...", "Tagging 10/50...").
        result (Optional[TrendAnalysisResponse]): The final analysis result
            when status is 'completed'.
        error (Optional[str]): Error message if status is 'failed'.
    """
    task_id: str
    status: str  # 'pending', 'processing', 'completed', 'failed'
    progress: int  # 0-100
    message: str  # e.g. "Fetching from ArXiv...", "Tagging 10/50..."
    result: Optional[TrendAnalysisResponse] = None
    error: Optional[str] = None